name: belajar_dart_packages_library
description: A starting point for Dart libraries or applications.
version: 1.5.0
homepage: https://www.ifca.co.id
repository: https://github.com/fardiansyah1808/belajar_dart_packages_library.git

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
